import type { Prompt } from './prompt-model';

export const seedPrompts: Prompt[] = [
  { tweetId: '2107433940638457866', publishedAt: '2026-10-06T11:33:00Z', title: 'Clear up agent instructions', command: '/writing-for-agents', text: "/writing-for-agents my AGENTS.md is a hot mess, propose a series of restructurings that:\n\n- Remove no-ops\n- Use progressive disclosure\n- Move instructions to CODING_STANDARDS.md\n\nApply your work over three subagents, each more radical than the last. Create a single PR.\n\nAGENTS.md is the most common source of token inefficiency. This prompt kills it dead.", textOrigin: 'user-provided' },
  { tweetId: '2107077843859513769', publishedAt: '2026-10-05T11:58:00Z', title: 'Learn from review comments', command: '/retro', text: "/retro take a look at as many GitHub PR review comments as you have access to from my team. Create suggestions for updates to CODING_STANDARDS.md (breaking into multiple files as needed).\n\nMakes your PR comments inform the code going forward.", textOrigin: 'user-provided' },
  { tweetId: '2106730768789602313', publishedAt: '2026-10-04T12:58:51Z', title: 'Review the skills update', command: null, text: "1. Re-check mattpocock/skills for the v1.3 release. Rename CONTEXT.md to GLOSSARY.md. Check /setup-matt-pocock-skills for any required changes. Perform a diff of the skills in my repository vs Matt's.\n\n2. Get a sense for how I use Matt's skills: scan my last 25 sessions for skill invocations. Then, recommend how this release might improve my workflow.", textOrigin: 'user-provided' },
  { tweetId: '2105951409887949107', publishedAt: '2026-10-02T09:21:57Z', title: 'Make a repo easier to navigate', command: '/retro', text: "/retro read my last 10 coding agent sessions and find ways to make my repo easier to navigate. Find where agents take too long to find relevant information, or rely on out-of-date docs.\n\nImproving navigability is such an underrated way to save tokens.", textOrigin: 'user-provided' },
  { tweetId: '2105563604384915639', publishedAt: '2026-10-01T07:40:57Z', title: 'Find unnecessary abstractions', command: '/codebase-design', text: '/codebase-design Take a look in the repo for shallow modules, applying the deletion test and look for candidates for deletion.', textOrigin: 'short-original' },
];
